name: sparemart2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  firebase_messaging: ^15.1.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.2
  awesome_dialog: ^3.2.1
  google_fonts:
  provider: ^6.1.2
  lottie: ^3.3.0
  ionicons: ^0.2.2
  card_swiper: ^3.0.1
  fancy_button_flutter: ^1.0.3+1
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/Lottie/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/brake.png"
  min_sdk_android: 23
  adaptive_icon_background: "#D8A7FF"
  adaptive_icon_foreground: "assets/brake.png"
